### ANOVA analysis

Now that we have explored and filtered the data, we can proceed with the ANOVA analysis.

#### Prepare the data for ANOVA

To avoid giving excessive weight to repeated trials (at least 2 for each direction as indicated in the experimental design), movement time was averaged for each participant (SUBJ), group (GROUP) and index of difficulty (ID). The resulting dataset contained one mean movement time value per participant and difficulty level and was used for the subsequent statistical analysis. 
#### Run the ANOVA


```{r }

S <- data_final|>
  group_by(GROUP, SUBJ, ID) |>
  summarise(MT = mean(MovementTime), .groups = "drop")
res <- anova_test(data = S, dv = MT, wid = SUBJ,
                  between = GROUP, within = ID)
anova_tab <- get_anova_table(res)

anova_tab

```

#### Interpret the ANOVA results

**Group effect : ** The 3 groups (ap, cp, pp) were compared to each other. The ANOVA results showed a significant effect of GROUP on movement time (F(2, 27) = 4.23, p = 0.025). This indicates that the mean movement time differed significantly between the three groups.

**ID effect** : The two levels of ID (ID1, ID2) were compared to each other. The ANOVA results showed a significant effect of ID on movement time (F(1, 27) = 5.67, p = 0.024). This indicates that the mean movement time differed significantly between the two levels of ID. When the ID increased, the movement time increased as well.





#### Plot the GROUP × ID interaction
